name: build-on-tag-windows
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
      - name: Configure and build project
        run: |
          mkdir build
          cd build
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake ../PiCalcQT.pro
          mingw32-make
        shell: cmd
      - name: Add missing DLLs
        run: |
          cd build\release
          copy D:/a/PiCalcQT/Qt/5.15.2/mingw81_64/bin/libwinpthread-1.dll
          copy D:/a/PiCalcQT/Qt/5.15.2/mingw81_64/bin/libstdc++-6.dll
          copy D:/a/PiCalcQT/Qt/5.15.2/mingw81_64/bin/libgcc_s_seh-1.dll
          windeployqt PiCalcQT.exe
          rm *.o
          rm *.cpp
      - name: Achive release
        run: |
          cd build
          powershell "Compress-Archive release PiCalcQT.zip"
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/PiCalcQT.zip
