name: qt-windows
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
      - name: Configure and build project
        run: |
          mkdir build
          cd build
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake ../PiCalcQT.pro
          mingw32-make 
        shell: cmd
      - name: Use QT Windows deployment tool
        run: |
          windeployqt build/release/PiCalcQT.exe
      - name: Achive release
        run: |
          cd build/release
          powershell "Compress-Archive * PiCalcQT.zip"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.2
          release_name: Beta 2
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/release/PiCalcQT.zip
          asset_name: PiCalcQT.zip
          asset_content_type: application/zip
